# Generated by Django 6.0.3 on 2026-05-06 19:41

import backend.wedding.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('groom_name', models.CharField(max_length=80)),
                ('bride_name', models.CharField(max_length=80)),
                ('venue_name', models.CharField(blank=True, max_length=160)),
                ('venue_address', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('upload_start', models.DateTimeField()),
                ('upload_end', models.DateTimeField()),
                ('invitation_title', models.CharField(blank=True, max_length=160)),
                ('invitation_text', models.TextField(blank=True)),
                ('couple_photo', models.FileField(blank=True, upload_to=backend.wedding.models.event_asset_path)),
                ('archive_cover', models.FileField(blank=True, upload_to=backend.wedding.models.event_asset_path)),
                ('videographer_film_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('is_vip', models.BooleanField(default=False)),
                ('position_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='wedding.weddingevent')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('password_hash', models.CharField(max_length=128)),
                ('avatar', models.FileField(blank=True, upload_to=backend.wedding.models.guest_avatar_path)),
                ('upload_override', models.CharField(choices=[('auto', 'Automatic schedule'), ('allow', 'Manual author'), ('deny', 'Manual blocked')], default='auto', help_text='AUTO uses event upload_start/upload_end; ALLOW grants; DENY blocks.', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='wedding.weddingevent')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='wedding.receptiontable')),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='TableSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='wedding.receptiontable')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='wedding.weddingevent')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='wedding.weddingguest')),
            ],
            options={
                'ordering': ['table__number', 'seat_number', 'guest__nickname'],
            },
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=8)),
                ('file', models.FileField(blank=True, upload_to=backend.wedding.models.media_upload_path)),
                ('external_url', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.FileField(blank=True, upload_to=backend.wedding.models.media_upload_path)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='approved', max_length=12)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_posts', to='wedding.weddingevent')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_posts', to='wedding.weddingguest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wedding.mediapost')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wedding.weddingguest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wedding.mediapost')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wedding.weddingguest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='receptiontable',
            constraint=models.UniqueConstraint(fields=('event', 'number'), name='unique_table_number_per_event'),
        ),
        migrations.AddConstraint(
            model_name='receptiontable',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_table_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='weddingguest',
            constraint=models.UniqueConstraint(fields=('event', 'nickname'), name='unique_guest_nickname_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tableseat',
            constraint=models.UniqueConstraint(fields=('event', 'guest'), name='unique_guest_seat_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tableseat',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_number__isnull', False)), fields=('table', 'seat_number'), name='unique_numbered_seat_per_table'),
        ),
        migrations.AddIndex(
            model_name='mediapost',
            index=models.Index(fields=['event', '-created_at'], name='wedding_med_event_i_7e97bf_idx'),
        ),
        migrations.AddIndex(
            model_name='mediapost',
            index=models.Index(fields=['event', 'status', '-created_at'], name='wedding_med_event_i_f559d3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediapost',
            index=models.Index(fields=['author', '-created_at'], name='wedding_med_author__ee9ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='medialike',
            constraint=models.UniqueConstraint(fields=('post', 'guest'), name='unique_like_per_guest_post'),
        ),
        migrations.AddIndex(
            model_name='mediacomment',
            index=models.Index(fields=['post', 'status', 'created_at'], name='wedding_med_post_id_032e10_idx'),
        ),
    ]
