# Generated by Django 6.0.3 on 2026-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=8),
        ),
    ]
