# Generated by Django 6.0.3 on 2026-05-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_uploadaccessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadaccessrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на загрузку', 'verbose_name_plural': 'Заявки на загрузку'},
        ),
    ]
